// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Batterie_arc;
lv_obj_t *ui_batterie_number;
lv_obj_t *ui_volt_;
lv_obj_t *ui_temperature_indic;
lv_obj_t *ui_temperature;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Panel2;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
lv_obj_t *ui_Screen2;
lv_obj_t *ui_voltage_choice;
lv_obj_t *ui_Roller1;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Panel4;
// CUSTOM VARIABLES
lv_obj_t *uic_Screen2;
lv_obj_t *uic_Dropdown2;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3( lv_event_t * e);
lv_obj_t *ui_Screen3;
lv_obj_t *ui_batterie11;
lv_obj_t *ui_batterie_12;
lv_obj_t *ui_batterie_21;
lv_obj_t *ui_batterie_22;
lv_obj_t *ui_batterie_31;
lv_obj_t *ui_batterie_32;
lv_obj_t *ui_batterie_41;
lv_obj_t *ui_batterie_42;
lv_obj_t *ui_batterie_51;
lv_obj_t *ui_batterie_52;
lv_obj_t *ui_batterie_61;
lv_obj_t *ui_batterie_62;
lv_obj_t *ui_batterie_71;
lv_obj_t *ui_batterie_72;
lv_obj_t *ui_batterie_81;
lv_obj_t *ui_batterie_82;
lv_obj_t *ui_batterie_91;
lv_obj_t *ui_batterie_92;
lv_obj_t *ui_batterie_101;
lv_obj_t *ui_batterie_102;
lv_obj_t *ui_batterie_111;
lv_obj_t *ui_batterie_112;
lv_obj_t *ui_batt_1;
lv_obj_t *ui_batt_2;
lv_obj_t *ui_batt_3;
lv_obj_t *ui_batt_4;
lv_obj_t *ui_batt_5;
lv_obj_t *ui_batt_6;
lv_obj_t *ui_batt_7;
lv_obj_t *ui_batt_8;
lv_obj_t *ui_batt_9;
lv_obj_t *ui_batt_10;
lv_obj_t *ui_batt_11;
lv_obj_t *ui_num1;
lv_obj_t *ui_num2;
lv_obj_t *ui_num3;
lv_obj_t *ui_num_4;
lv_obj_t *ui_num5;
lv_obj_t *ui_num6;
lv_obj_t *ui_num7;
lv_obj_t *ui_num8;
lv_obj_t *ui_num9;
lv_obj_t *ui_num10;
lv_obj_t *ui_num11;
lv_obj_t *ui_n1_;
lv_obj_t *ui_n2_;
lv_obj_t *ui_n3_;
lv_obj_t *ui_n4_;
lv_obj_t *ui_n5_;
lv_obj_t *ui_n6_;
lv_obj_t *ui_n7_;
lv_obj_t *ui_n8_;
lv_obj_t *ui_n9_;
lv_obj_t *ui_n10_;
lv_obj_t *ui_n11_;
lv_obj_t *ui_tension_1;
lv_obj_t *ui_tension_2;
lv_obj_t *ui_tension_3;
lv_obj_t *ui_tension_4;
lv_obj_t *ui_tension_5;
lv_obj_t *ui_tension_6;
lv_obj_t *ui_tension_7;
lv_obj_t *ui_tension_8;
lv_obj_t *ui_tension_9;
lv_obj_t *ui_tension_10;
lv_obj_t *ui_tension_11;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_Panel6;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_1233108270[2] = {&ui_img_1850710409, &ui_img_1850708359};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 400, 3, &ui_Screen2_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen3_screen_init);
}
}

void ui_event_Screen2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen3_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
}
}

void ui_event_Screen3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen1_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui_Screen2_screen_init();
ui_Screen3_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
