// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Batterie_arc;
extern lv_obj_t *ui_batterie_number;
extern lv_obj_t *ui_volt_;
extern lv_obj_t *ui_temperature_indic;
extern lv_obj_t *ui_temperature;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Panel2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_voltage_choice;
extern lv_obj_t *ui_Roller1;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Panel4;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Screen2;
extern lv_obj_t *uic_Dropdown2;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3( lv_event_t * e);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_batterie11;
extern lv_obj_t *ui_batterie_12;
extern lv_obj_t *ui_batterie_21;
extern lv_obj_t *ui_batterie_22;
extern lv_obj_t *ui_batterie_31;
extern lv_obj_t *ui_batterie_32;
extern lv_obj_t *ui_batterie_41;
extern lv_obj_t *ui_batterie_42;
extern lv_obj_t *ui_batterie_51;
extern lv_obj_t *ui_batterie_52;
extern lv_obj_t *ui_batterie_61;
extern lv_obj_t *ui_batterie_62;
extern lv_obj_t *ui_batterie_71;
extern lv_obj_t *ui_batterie_72;
extern lv_obj_t *ui_batterie_81;
extern lv_obj_t *ui_batterie_82;
extern lv_obj_t *ui_batterie_91;
extern lv_obj_t *ui_batterie_92;
extern lv_obj_t *ui_batterie_101;
extern lv_obj_t *ui_batterie_102;
extern lv_obj_t *ui_batterie_111;
extern lv_obj_t *ui_batterie_112;
extern lv_obj_t *ui_batt_1;
extern lv_obj_t *ui_batt_2;
extern lv_obj_t *ui_batt_3;
extern lv_obj_t *ui_batt_4;
extern lv_obj_t *ui_batt_5;
extern lv_obj_t *ui_batt_6;
extern lv_obj_t *ui_batt_7;
extern lv_obj_t *ui_batt_8;
extern lv_obj_t *ui_batt_9;
extern lv_obj_t *ui_batt_10;
extern lv_obj_t *ui_batt_11;
extern lv_obj_t *ui_num1;
extern lv_obj_t *ui_num2;
extern lv_obj_t *ui_num3;
extern lv_obj_t *ui_num_4;
extern lv_obj_t *ui_num5;
extern lv_obj_t *ui_num6;
extern lv_obj_t *ui_num7;
extern lv_obj_t *ui_num8;
extern lv_obj_t *ui_num9;
extern lv_obj_t *ui_num10;
extern lv_obj_t *ui_num11;
extern lv_obj_t *ui_n1_;
extern lv_obj_t *ui_n2_;
extern lv_obj_t *ui_n3_;
extern lv_obj_t *ui_n4_;
extern lv_obj_t *ui_n5_;
extern lv_obj_t *ui_n6_;
extern lv_obj_t *ui_n7_;
extern lv_obj_t *ui_n8_;
extern lv_obj_t *ui_n9_;
extern lv_obj_t *ui_n10_;
extern lv_obj_t *ui_n11_;
extern lv_obj_t *ui_tension_1;
extern lv_obj_t *ui_tension_2;
extern lv_obj_t *ui_tension_3;
extern lv_obj_t *ui_tension_4;
extern lv_obj_t *ui_tension_5;
extern lv_obj_t *ui_tension_6;
extern lv_obj_t *ui_tension_7;
extern lv_obj_t *ui_tension_8;
extern lv_obj_t *ui_tension_9;
extern lv_obj_t *ui_tension_10;
extern lv_obj_t *ui_tension_11;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Panel6;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1850710409);   // assets/Nouveau projet-2.png
LV_IMG_DECLARE( ui_img_239239933);   // assets/images-2-removebg-preview.png
LV_IMG_DECLARE( ui_img_1850708359);   // assets/Nouveau projet-4.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
