// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_add_flag( ui_Screen2, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK );   /// Flags
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_main_stop(ui_Screen2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Screen2, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Screen2, 2, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Screen2, 2, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Screen2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Screen2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Screen2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Screen2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_voltage_choice = lv_dropdown_create(ui_Screen2);
lv_dropdown_set_options( ui_voltage_choice, "42 V\n36 V\n24 V \n12 V" );
lv_obj_set_width( ui_voltage_choice, 121);
lv_obj_set_height( ui_voltage_choice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_voltage_choice, 71 );
lv_obj_set_y( ui_voltage_choice, -72 );
lv_obj_set_align( ui_voltage_choice, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_voltage_choice, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_voltage_choice, lv_color_hex(0x049DAB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_voltage_choice, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_voltage_choice, lv_color_hex(0x00353D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_voltage_choice, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_voltage_choice, lv_color_hex(0x002227), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_voltage_choice, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_voltage_choice, lv_color_hex(0x00353D), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_voltage_choice, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_voltage_choice), lv_color_hex(0x049DAB),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_voltage_choice), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_voltage_choice), lv_color_hex(0x00353D),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_voltage_choice), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(lv_dropdown_get_list(ui_voltage_choice), lv_color_hex(0x00353D),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(lv_dropdown_get_list(ui_voltage_choice), lv_color_hex(0x001C20),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_voltage_choice), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_voltage_choice), lv_color_hex(0x049DAB),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_voltage_choice), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Roller1 = lv_roller_create(ui_Screen2);
lv_roller_set_options( ui_Roller1, "Max charge \n\nDefault Set\n\nMax discharge", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_Roller1, 113);
lv_obj_set_height( ui_Roller1, 164);
lv_obj_set_x( ui_Roller1, -74 );
lv_obj_set_y( ui_Roller1, -5 );
lv_obj_set_align( ui_Roller1, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_Roller1, lv_color_hex(0x008E9C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller1, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x000407), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Roller1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Roller1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Roller1, lv_color_hex(0x056B74), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller1, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller1, &lv_font_montserrat_14, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x003439), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller1, 66, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Panel3, 314);
lv_obj_set_height( ui_Panel3, 31);
lv_obj_set_x( ui_Panel3, -3 );
lv_obj_set_y( ui_Panel3, -110 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x001018), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Panel4, 314);
lv_obj_set_height( ui_Panel4, 31);
lv_obj_set_x( ui_Panel4, 5 );
lv_obj_set_y( ui_Panel4, 108 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x001018), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);
uic_Screen2 = ui_Screen2;
uic_Dropdown2 = ui_voltage_choice;

}
