// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Screen3, lv_color_hex(0x0E1D1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Screen3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batterie11 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie11, &ui_img_239239933);
lv_obj_set_width( ui_batterie11, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie11, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie11, -103 );
lv_obj_set_y( ui_batterie11, -72 );
lv_obj_set_align( ui_batterie11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie11, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie11,2700);
lv_img_set_zoom(ui_batterie11,100);

ui_batterie_12 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_12, &ui_img_239239933);
lv_obj_set_width( ui_batterie_12, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_12, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_12, -77 );
lv_obj_set_y( ui_batterie_12, -72 );
lv_obj_set_align( ui_batterie_12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_12, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_12,2700);
lv_img_set_zoom(ui_batterie_12,100);

ui_batterie_21 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_21, &ui_img_239239933);
lv_obj_set_width( ui_batterie_21, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_21, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_21, -45 );
lv_obj_set_y( ui_batterie_21, -71 );
lv_obj_set_align( ui_batterie_21, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_21, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_21, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_21,2700);
lv_img_set_zoom(ui_batterie_21,100);

ui_batterie_22 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_22, &ui_img_239239933);
lv_obj_set_width( ui_batterie_22, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_22, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_22, -18 );
lv_obj_set_y( ui_batterie_22, -71 );
lv_obj_set_align( ui_batterie_22, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_22, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_22, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_22,2700);
lv_img_set_zoom(ui_batterie_22,100);

ui_batterie_31 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_31, &ui_img_239239933);
lv_obj_set_width( ui_batterie_31, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_31, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_31, 14 );
lv_obj_set_y( ui_batterie_31, -71 );
lv_obj_set_align( ui_batterie_31, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_31, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_31, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_31,2700);
lv_img_set_zoom(ui_batterie_31,100);

ui_batterie_32 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_32, &ui_img_239239933);
lv_obj_set_width( ui_batterie_32, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_32, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_32, 41 );
lv_obj_set_y( ui_batterie_32, -71 );
lv_obj_set_align( ui_batterie_32, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_32, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_32, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_32,2700);
lv_img_set_zoom(ui_batterie_32,100);

ui_batterie_41 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_41, &ui_img_239239933);
lv_obj_set_width( ui_batterie_41, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_41, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_41, 73 );
lv_obj_set_y( ui_batterie_41, -70 );
lv_obj_set_align( ui_batterie_41, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_41, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_41, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_41,2700);
lv_img_set_zoom(ui_batterie_41,100);

ui_batterie_42 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_42, &ui_img_239239933);
lv_obj_set_width( ui_batterie_42, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_42, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_42, 100 );
lv_obj_set_y( ui_batterie_42, -70 );
lv_obj_set_align( ui_batterie_42, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_42, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_42, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_42,2700);
lv_img_set_zoom(ui_batterie_42,100);

ui_batterie_51 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_51, &ui_img_239239933);
lv_obj_set_width( ui_batterie_51, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_51, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_51, -103 );
lv_obj_set_y( ui_batterie_51, 6 );
lv_obj_set_align( ui_batterie_51, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_51, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_51, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_51,2700);
lv_img_set_zoom(ui_batterie_51,100);

ui_batterie_52 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_52, &ui_img_239239933);
lv_obj_set_width( ui_batterie_52, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_52, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_52, -77 );
lv_obj_set_y( ui_batterie_52, 6 );
lv_obj_set_align( ui_batterie_52, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_52, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_52, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_52,2700);
lv_img_set_zoom(ui_batterie_52,100);

ui_batterie_61 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_61, &ui_img_239239933);
lv_obj_set_width( ui_batterie_61, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_61, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_61, -45 );
lv_obj_set_y( ui_batterie_61, 6 );
lv_obj_set_align( ui_batterie_61, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_61, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_61, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_61,2700);
lv_img_set_zoom(ui_batterie_61,100);

ui_batterie_62 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_62, &ui_img_239239933);
lv_obj_set_width( ui_batterie_62, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_62, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_62, -18 );
lv_obj_set_y( ui_batterie_62, 6 );
lv_obj_set_align( ui_batterie_62, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_62, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_62, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_62,2700);
lv_img_set_zoom(ui_batterie_62,100);

ui_batterie_71 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_71, &ui_img_239239933);
lv_obj_set_width( ui_batterie_71, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_71, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_71, 14 );
lv_obj_set_y( ui_batterie_71, 6 );
lv_obj_set_align( ui_batterie_71, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_71, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_71, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_71,2700);
lv_img_set_zoom(ui_batterie_71,100);

ui_batterie_72 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_72, &ui_img_239239933);
lv_obj_set_width( ui_batterie_72, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_72, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_72, 41 );
lv_obj_set_y( ui_batterie_72, 6 );
lv_obj_set_align( ui_batterie_72, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_72, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_72, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_72,2700);
lv_img_set_zoom(ui_batterie_72,100);

ui_batterie_81 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_81, &ui_img_239239933);
lv_obj_set_width( ui_batterie_81, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_81, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_81, 73 );
lv_obj_set_y( ui_batterie_81, 6 );
lv_obj_set_align( ui_batterie_81, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_81, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_81, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_81,2700);
lv_img_set_zoom(ui_batterie_81,100);

ui_batterie_82 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_82, &ui_img_239239933);
lv_obj_set_width( ui_batterie_82, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_82, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_82, 100 );
lv_obj_set_y( ui_batterie_82, 6 );
lv_obj_set_align( ui_batterie_82, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_82, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_82, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_82,2700);
lv_img_set_zoom(ui_batterie_82,100);

ui_batterie_91 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_91, &ui_img_239239933);
lv_obj_set_width( ui_batterie_91, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_91, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_91, -74 );
lv_obj_set_y( ui_batterie_91, 84 );
lv_obj_set_align( ui_batterie_91, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_91, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_91, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_91,2700);
lv_img_set_zoom(ui_batterie_91,100);

ui_batterie_92 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_92, &ui_img_239239933);
lv_obj_set_width( ui_batterie_92, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_92, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_92, -47 );
lv_obj_set_y( ui_batterie_92, 84 );
lv_obj_set_align( ui_batterie_92, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_92, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_92, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_92,2700);
lv_img_set_zoom(ui_batterie_92,100);

ui_batterie_101 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_101, &ui_img_239239933);
lv_obj_set_width( ui_batterie_101, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_101, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_101, -15 );
lv_obj_set_y( ui_batterie_101, 84 );
lv_obj_set_align( ui_batterie_101, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_101, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_101, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_101,2700);
lv_img_set_zoom(ui_batterie_101,100);

ui_batterie_102 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_102, &ui_img_239239933);
lv_obj_set_width( ui_batterie_102, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_102, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_102, 11 );
lv_obj_set_y( ui_batterie_102, 84 );
lv_obj_set_align( ui_batterie_102, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_102, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_102, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_102,2700);
lv_img_set_zoom(ui_batterie_102,100);

ui_batterie_111 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_111, &ui_img_239239933);
lv_obj_set_width( ui_batterie_111, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_111, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_111, 43 );
lv_obj_set_y( ui_batterie_111, 84 );
lv_obj_set_align( ui_batterie_111, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_111, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_111, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_111,2700);
lv_img_set_zoom(ui_batterie_111,100);

ui_batterie_112 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_batterie_112, &ui_img_239239933);
lv_obj_set_width( ui_batterie_112, LV_SIZE_CONTENT);  /// 225
lv_obj_set_height( ui_batterie_112, LV_SIZE_CONTENT);   /// 225
lv_obj_set_x( ui_batterie_112, 70 );
lv_obj_set_y( ui_batterie_112, 84 );
lv_obj_set_align( ui_batterie_112, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_batterie_112, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_batterie_112, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_batterie_112,2700);
lv_img_set_zoom(ui_batterie_112,100);

ui_batt_1 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_batt_1, 46);
lv_obj_set_height( ui_batt_1, 14);
lv_obj_set_x( ui_batt_1, -88 );
lv_obj_set_y( ui_batt_1, -110 );
lv_obj_set_align( ui_batt_1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_batt_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_batt_1, lv_color_hex(0x00353D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batt_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batt_1, lv_color_hex(0x001011), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batt_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batt_2 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_batt_2, 46);
lv_obj_set_height( ui_batt_2, 14);
lv_obj_set_x( ui_batt_2, -31 );
lv_obj_set_y( ui_batt_2, -110 );
lv_obj_set_align( ui_batt_2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_batt_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_batt_2, lv_color_hex(0x00353D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batt_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batt_2, lv_color_hex(0x001011), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batt_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batt_3 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_batt_3, 46);
lv_obj_set_height( ui_batt_3, 14);
lv_obj_set_x( ui_batt_3, 27 );
lv_obj_set_y( ui_batt_3, -110 );
lv_obj_set_align( ui_batt_3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_batt_3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_batt_3, lv_color_hex(0x00353D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batt_3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batt_3, lv_color_hex(0x001011), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batt_3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batt_4 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_batt_4, 46);
lv_obj_set_height( ui_batt_4, 14);
lv_obj_set_x( ui_batt_4, 85 );
lv_obj_set_y( ui_batt_4, -110 );
lv_obj_set_align( ui_batt_4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_batt_4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_batt_4, lv_color_hex(0x00353D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batt_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batt_4, lv_color_hex(0x001011), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batt_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batt_5 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_batt_5, 46);
lv_obj_set_height( ui_batt_5, 14);
lv_obj_set_x( ui_batt_5, -89 );
lv_obj_set_y( ui_batt_5, -32 );
lv_obj_set_align( ui_batt_5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_batt_5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_batt_5, lv_color_hex(0x00353D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batt_5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batt_5, lv_color_hex(0x001011), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batt_5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batt_6 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_batt_6, 46);
lv_obj_set_height( ui_batt_6, 14);
lv_obj_set_x( ui_batt_6, -31 );
lv_obj_set_y( ui_batt_6, -32 );
lv_obj_set_align( ui_batt_6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_batt_6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_batt_6, lv_color_hex(0x00353D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batt_6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batt_6, lv_color_hex(0x001011), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batt_6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batt_7 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_batt_7, 46);
lv_obj_set_height( ui_batt_7, 14);
lv_obj_set_x( ui_batt_7, 27 );
lv_obj_set_y( ui_batt_7, -32 );
lv_obj_set_align( ui_batt_7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_batt_7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_batt_7, lv_color_hex(0x00353D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batt_7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batt_7, lv_color_hex(0x001011), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batt_7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batt_8 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_batt_8, 46);
lv_obj_set_height( ui_batt_8, 14);
lv_obj_set_x( ui_batt_8, 86 );
lv_obj_set_y( ui_batt_8, -32 );
lv_obj_set_align( ui_batt_8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_batt_8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_batt_8, lv_color_hex(0x00353D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batt_8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batt_8, lv_color_hex(0x001011), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batt_8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batt_9 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_batt_9, 46);
lv_obj_set_height( ui_batt_9, 14);
lv_obj_set_x( ui_batt_9, -59 );
lv_obj_set_y( ui_batt_9, 46 );
lv_obj_set_align( ui_batt_9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_batt_9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_batt_9, lv_color_hex(0x00353D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batt_9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batt_9, lv_color_hex(0x001011), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batt_9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batt_10 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_batt_10, 46);
lv_obj_set_height( ui_batt_10, 14);
lv_obj_set_x( ui_batt_10, -1 );
lv_obj_set_y( ui_batt_10, 46 );
lv_obj_set_align( ui_batt_10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_batt_10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_batt_10, lv_color_hex(0x00353D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batt_10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batt_10, lv_color_hex(0x001011), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batt_10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batt_11 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_batt_11, 46);
lv_obj_set_height( ui_batt_11, 14);
lv_obj_set_x( ui_batt_11, 57 );
lv_obj_set_y( ui_batt_11, 46 );
lv_obj_set_align( ui_batt_11, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_batt_11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_batt_11, lv_color_hex(0x00353D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batt_11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batt_11, lv_color_hex(0x001011), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batt_11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_num1 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_num1, 22);
lv_obj_set_height( ui_num1, 19);
lv_obj_set_x( ui_num1, -88 );
lv_obj_set_y( ui_num1, -69 );
lv_obj_set_align( ui_num1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_num1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_num1, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_num1, lv_color_hex(0x012C33), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_num1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_num1, lv_color_hex(0x0E1D1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_num1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_num2 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_num2, 22);
lv_obj_set_height( ui_num2, 19);
lv_obj_set_x( ui_num2, -30 );
lv_obj_set_y( ui_num2, -69 );
lv_obj_set_align( ui_num2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_num2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_num2, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_num2, lv_color_hex(0x012C33), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_num2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_num2, lv_color_hex(0x0E1D1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_num2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_num3 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_num3, 22);
lv_obj_set_height( ui_num3, 19);
lv_obj_set_x( ui_num3, 27 );
lv_obj_set_y( ui_num3, -69 );
lv_obj_set_align( ui_num3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_num3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_num3, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_num3, lv_color_hex(0x012C33), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_num3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_num3, lv_color_hex(0x0E1D1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_num3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_num_4 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_num_4, 22);
lv_obj_set_height( ui_num_4, 19);
lv_obj_set_x( ui_num_4, 86 );
lv_obj_set_y( ui_num_4, -68 );
lv_obj_set_align( ui_num_4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_num_4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_num_4, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_num_4, lv_color_hex(0x012C33), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_num_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_num_4, lv_color_hex(0x0E1D1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_num_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_num5 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_num5, 22);
lv_obj_set_height( ui_num5, 19);
lv_obj_set_x( ui_num5, -89 );
lv_obj_set_y( ui_num5, 9 );
lv_obj_set_align( ui_num5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_num5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_num5, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_num5, lv_color_hex(0x012C33), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_num5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_num5, lv_color_hex(0x0E1D1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_num5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_num6 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_num6, 22);
lv_obj_set_height( ui_num6, 19);
lv_obj_set_x( ui_num6, -30 );
lv_obj_set_y( ui_num6, 9 );
lv_obj_set_align( ui_num6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_num6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_num6, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_num6, lv_color_hex(0x012C33), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_num6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_num6, lv_color_hex(0x0E1D1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_num6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_num7 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_num7, 22);
lv_obj_set_height( ui_num7, 19);
lv_obj_set_x( ui_num7, 28 );
lv_obj_set_y( ui_num7, 8 );
lv_obj_set_align( ui_num7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_num7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_num7, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_num7, lv_color_hex(0x012C33), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_num7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_num7, lv_color_hex(0x0E1D1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_num7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_num8 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_num8, 22);
lv_obj_set_height( ui_num8, 19);
lv_obj_set_x( ui_num8, 87 );
lv_obj_set_y( ui_num8, 8 );
lv_obj_set_align( ui_num8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_num8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_num8, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_num8, lv_color_hex(0x012C33), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_num8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_num8, lv_color_hex(0x0E1D1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_num8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_num9 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_num9, 22);
lv_obj_set_height( ui_num9, 19);
lv_obj_set_x( ui_num9, -60 );
lv_obj_set_y( ui_num9, 87 );
lv_obj_set_align( ui_num9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_num9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_num9, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_num9, lv_color_hex(0x012C33), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_num9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_num9, lv_color_hex(0x0E1D1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_num9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_num10 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_num10, 22);
lv_obj_set_height( ui_num10, 19);
lv_obj_set_x( ui_num10, -1 );
lv_obj_set_y( ui_num10, 87 );
lv_obj_set_align( ui_num10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_num10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_num10, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_num10, lv_color_hex(0x012C33), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_num10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_num10, lv_color_hex(0x0E1D1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_num10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_num11 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_num11, 22);
lv_obj_set_height( ui_num11, 19);
lv_obj_set_x( ui_num11, 57 );
lv_obj_set_y( ui_num11, 87 );
lv_obj_set_align( ui_num11, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_num11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_num11, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_num11, lv_color_hex(0x012C33), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_num11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_num11, lv_color_hex(0x0E1D1D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_num11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_n1_ = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_n1_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_n1_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_n1_, -88 );
lv_obj_set_y( ui_n1_, -69 );
lv_obj_set_align( ui_n1_, LV_ALIGN_CENTER );
lv_label_set_text(ui_n1_,"1");
lv_obj_set_style_text_color(ui_n1_, lv_color_hex(0x03838F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_n1_, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_n1_, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_n2_ = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_n2_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_n2_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_n2_, -31 );
lv_obj_set_y( ui_n2_, -69 );
lv_obj_set_align( ui_n2_, LV_ALIGN_CENTER );
lv_label_set_text(ui_n2_,"2");
lv_obj_set_style_text_color(ui_n2_, lv_color_hex(0x03838F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_n2_, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_n2_, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_n3_ = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_n3_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_n3_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_n3_, 27 );
lv_obj_set_y( ui_n3_, -69 );
lv_obj_set_align( ui_n3_, LV_ALIGN_CENTER );
lv_label_set_text(ui_n3_,"3");
lv_obj_set_style_text_color(ui_n3_, lv_color_hex(0x03838F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_n3_, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_n3_, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_n4_ = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_n4_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_n4_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_n4_, 86 );
lv_obj_set_y( ui_n4_, -68 );
lv_obj_set_align( ui_n4_, LV_ALIGN_CENTER );
lv_label_set_text(ui_n4_,"4");
lv_obj_set_style_text_color(ui_n4_, lv_color_hex(0x03838F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_n4_, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_n4_, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_n5_ = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_n5_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_n5_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_n5_, -89 );
lv_obj_set_y( ui_n5_, 9 );
lv_obj_set_align( ui_n5_, LV_ALIGN_CENTER );
lv_label_set_text(ui_n5_,"5");
lv_obj_set_style_text_color(ui_n5_, lv_color_hex(0x03838F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_n5_, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_n5_, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_n6_ = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_n6_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_n6_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_n6_, -31 );
lv_obj_set_y( ui_n6_, 9 );
lv_obj_set_align( ui_n6_, LV_ALIGN_CENTER );
lv_label_set_text(ui_n6_,"6");
lv_obj_set_style_text_color(ui_n6_, lv_color_hex(0x03838F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_n6_, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_n6_, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_n7_ = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_n7_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_n7_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_n7_, 27 );
lv_obj_set_y( ui_n7_, 8 );
lv_obj_set_align( ui_n7_, LV_ALIGN_CENTER );
lv_label_set_text(ui_n7_,"7");
lv_obj_set_style_text_color(ui_n7_, lv_color_hex(0x03838F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_n7_, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_n7_, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_n8_ = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_n8_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_n8_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_n8_, 87 );
lv_obj_set_y( ui_n8_, 8 );
lv_obj_set_align( ui_n8_, LV_ALIGN_CENTER );
lv_label_set_text(ui_n8_,"8");
lv_obj_set_style_text_color(ui_n8_, lv_color_hex(0x03838F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_n8_, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_n8_, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_n9_ = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_n9_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_n9_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_n9_, -60 );
lv_obj_set_y( ui_n9_, 87 );
lv_obj_set_align( ui_n9_, LV_ALIGN_CENTER );
lv_label_set_text(ui_n9_,"9");
lv_obj_set_style_text_color(ui_n9_, lv_color_hex(0x03838F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_n9_, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_n9_, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_n10_ = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_n10_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_n10_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_n10_, -1 );
lv_obj_set_y( ui_n10_, 87 );
lv_obj_set_align( ui_n10_, LV_ALIGN_CENTER );
lv_label_set_text(ui_n10_,"10");
lv_obj_set_style_text_color(ui_n10_, lv_color_hex(0x03838F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_n10_, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_n10_, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_n11_ = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_n11_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_n11_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_n11_, 57 );
lv_obj_set_y( ui_n11_, 88 );
lv_obj_set_align( ui_n11_, LV_ALIGN_CENTER );
lv_label_set_text(ui_n11_,"11");
lv_obj_set_style_text_color(ui_n11_, lv_color_hex(0x03838F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_n11_, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_n11_, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tension_1 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_tension_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tension_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tension_1, -88 );
lv_obj_set_y( ui_tension_1, -110 );
lv_obj_set_align( ui_tension_1, LV_ALIGN_CENTER );
lv_label_set_text(ui_tension_1,"3.7v");
lv_obj_set_style_text_color(ui_tension_1, lv_color_hex(0x0393A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tension_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tension_1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tension_2 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_tension_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tension_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tension_2, -29 );
lv_obj_set_y( ui_tension_2, -111 );
lv_obj_set_align( ui_tension_2, LV_ALIGN_CENTER );
lv_label_set_text(ui_tension_2,"3.7v");
lv_obj_set_style_text_color(ui_tension_2, lv_color_hex(0x0393A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tension_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tension_2, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tension_3 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_tension_3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tension_3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tension_3, 30 );
lv_obj_set_y( ui_tension_3, -110 );
lv_obj_set_align( ui_tension_3, LV_ALIGN_CENTER );
lv_label_set_text(ui_tension_3,"3.7v");
lv_obj_set_style_text_color(ui_tension_3, lv_color_hex(0x0393A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tension_3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tension_3, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tension_4 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_tension_4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tension_4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tension_4, 87 );
lv_obj_set_y( ui_tension_4, -110 );
lv_obj_set_align( ui_tension_4, LV_ALIGN_CENTER );
lv_label_set_text(ui_tension_4,"3.7v");
lv_obj_set_style_text_color(ui_tension_4, lv_color_hex(0x0393A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tension_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tension_4, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tension_5 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_tension_5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tension_5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tension_5, -88 );
lv_obj_set_y( ui_tension_5, -32 );
lv_obj_set_align( ui_tension_5, LV_ALIGN_CENTER );
lv_label_set_text(ui_tension_5,"3.7v");
lv_obj_set_style_text_color(ui_tension_5, lv_color_hex(0x0393A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tension_5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tension_5, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tension_6 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_tension_6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tension_6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tension_6, -29 );
lv_obj_set_y( ui_tension_6, -32 );
lv_obj_set_align( ui_tension_6, LV_ALIGN_CENTER );
lv_label_set_text(ui_tension_6,"3.7v");
lv_obj_set_style_text_color(ui_tension_6, lv_color_hex(0x0393A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tension_6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tension_6, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tension_7 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_tension_7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tension_7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tension_7, 29 );
lv_obj_set_y( ui_tension_7, -32 );
lv_obj_set_align( ui_tension_7, LV_ALIGN_CENTER );
lv_label_set_text(ui_tension_7,"3.7v");
lv_obj_set_style_text_color(ui_tension_7, lv_color_hex(0x0393A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tension_7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tension_7, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tension_8 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_tension_8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tension_8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tension_8, 88 );
lv_obj_set_y( ui_tension_8, -32 );
lv_obj_set_align( ui_tension_8, LV_ALIGN_CENTER );
lv_label_set_text(ui_tension_8,"3.7v");
lv_obj_set_style_text_color(ui_tension_8, lv_color_hex(0x0393A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tension_8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tension_8, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tension_9 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_tension_9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tension_9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tension_9, -58 );
lv_obj_set_y( ui_tension_9, 46 );
lv_obj_set_align( ui_tension_9, LV_ALIGN_CENTER );
lv_label_set_text(ui_tension_9,"3.7v");
lv_obj_set_style_text_color(ui_tension_9, lv_color_hex(0x0393A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tension_9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tension_9, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tension_10 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_tension_10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tension_10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tension_10, 0 );
lv_obj_set_y( ui_tension_10, 46 );
lv_obj_set_align( ui_tension_10, LV_ALIGN_CENTER );
lv_label_set_text(ui_tension_10,"3.7v");
lv_obj_set_style_text_color(ui_tension_10, lv_color_hex(0x0393A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tension_10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tension_10, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tension_11 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_tension_11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tension_11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tension_11, 59 );
lv_obj_set_y( ui_tension_11, 46 );
lv_obj_set_align( ui_tension_11, LV_ALIGN_CENTER );
lv_label_set_text(ui_tension_11,"3.7v");
lv_obj_set_style_text_color(ui_tension_11, lv_color_hex(0x0393A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tension_11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tension_11, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);


}
