// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_add_flag( ui_Screen1, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK );   /// Flags
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_scroll_dir(ui_Screen1, LV_DIR_RIGHT);
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Batterie_arc = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Batterie_arc, 143);
lv_obj_set_height( ui_Batterie_arc, 145);
lv_obj_set_x( ui_Batterie_arc, -22 );
lv_obj_set_y( ui_Batterie_arc, 18 );
lv_obj_set_align( ui_Batterie_arc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Batterie_arc, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_value(ui_Batterie_arc, 50);
lv_obj_set_style_arc_color(ui_Batterie_arc, lv_color_hex(0x00353D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Batterie_arc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Batterie_arc, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Batterie_arc, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Batterie_arc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Batterie_arc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Batterie_arc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Batterie_arc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Batterie_arc, LV_GRAD_DIR_NONE, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_Batterie_arc, lv_color_hex(0x049DAB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Batterie_arc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Batterie_arc, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Batterie_arc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Batterie_arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Batterie_arc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Batterie_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Batterie_arc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Batterie_arc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Batterie_arc, LV_GRAD_DIR_NONE, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Batterie_arc, LV_BORDER_SIDE_NONE, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_batterie_number = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_batterie_number, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batterie_number, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batterie_number, -21 );
lv_obj_set_y( ui_batterie_number, 11 );
lv_obj_set_align( ui_batterie_number, LV_ALIGN_CENTER );
lv_label_set_text(ui_batterie_number,"0.00%");
lv_obj_set_style_text_color(ui_batterie_number, lv_color_hex(0x009EC0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_batterie_number, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batterie_number, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_volt_ = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_volt_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_volt_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_volt_, -109 );
lv_obj_set_y( ui_volt_, -76 );
lv_obj_set_align( ui_volt_, LV_ALIGN_CENTER );
lv_label_set_text(ui_volt_,"42 V");
lv_obj_clear_flag( ui_volt_, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_style_text_color(ui_volt_, lv_color_hex(0x00809C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_volt_, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_volt_, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temperature_indic = lv_bar_create(ui_Screen1);
lv_bar_set_value(ui_temperature_indic,100,LV_ANIM_OFF);
lv_bar_set_start_value(ui_temperature_indic, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_temperature_indic, 8);
lv_obj_set_height( ui_temperature_indic, 81);
lv_obj_set_x( ui_temperature_indic, 98 );
lv_obj_set_y( ui_temperature_indic, 14 );
lv_obj_set_align( ui_temperature_indic, LV_ALIGN_CENTER );

lv_obj_set_style_bg_color(ui_temperature_indic, lv_color_hex(0x56B1B9), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_temperature_indic, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_temperature = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_temperature, 12);
lv_obj_set_height( ui_temperature, 26);
lv_obj_set_x( ui_temperature, 99 );
lv_obj_set_y( ui_temperature, -29 );
lv_obj_set_align( ui_temperature, LV_ALIGN_CENTER );
lv_label_set_text(ui_temperature,"0");
lv_obj_set_style_text_color(ui_temperature, lv_color_hex(0x007993), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temperature, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temperature, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 342);
lv_obj_set_height( ui_Panel1, 26);
lv_obj_set_x( ui_Panel1, -1 );
lv_obj_set_y( ui_Panel1, -108 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 21, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x00131B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image3, &ui_img_1850710409);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 280
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 240
lv_obj_set_x( ui_Image3, 93 );
lv_obj_set_y( ui_Image3, 18 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image3,140);

ui_Panel2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel2, 342);
lv_obj_set_height( ui_Panel2, 26);
lv_obj_set_x( ui_Panel2, 6 );
lv_obj_set_y( ui_Panel2, 108 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2, 21, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x00131B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
