// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_1850710409);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 280
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 240
lv_obj_set_x( ui_Image1, 169 );
lv_obj_set_y( ui_Image1, 12 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc1 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc1, 216);
lv_obj_set_height( ui_Arc1, 195);
lv_obj_set_x( ui_Arc1, -88 );
lv_obj_set_y( ui_Arc1, 5 );
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
lv_arc_set_value(ui_Arc1, 50);

ui_Slider1 = lv_slider_create(ui_Screen1);
lv_slider_set_value( ui_Slider1, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider1, 150);
lv_obj_set_height( ui_Slider1, 10);
lv_obj_set_x( ui_Slider1, 0 );
lv_obj_set_y( ui_Slider1, -179 );
lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );

}
